### ISSUE TITLE
Racist terms in the training data

### ISSUE THREAD

**Issue by vallode** [dylanwenzlau/ml-scripts#1]
Not sure if you noticed this, but there are some (found one) racist terms in the training data.

https://github.com/dylanwenzlau/ml-scripts/blob/2cb7f289eb398532acf5db3c5c5d0c1da50db09a/meme_text_gen_convnet/training_data_sample.json#L171

**Comment by dylanwenzlau** [comment]
This was just a random sample from publicly created memes, I didn't curate it. You always find a few offensive things in a random sample. I'd recommend curating any training dataset you use if you want to avoid certain terms.
